//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactions_Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", ConfigurationName="Transactions_Service.Transactions_Port")]
    public interface Transactions_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.Read_Result Read(Transactions_Service.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.Read_Result> ReadAsync(Transactions_Service.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.ReadByRecId_Result ReadByRecId(Transactions_Service.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.ReadByRecId_Result> ReadByRecIdAsync(Transactions_Service.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.ReadMultiple_Result ReadMultiple(Transactions_Service.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.ReadMultiple_Result> ReadMultipleAsync(Transactions_Service.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.IsUpdated_Result IsUpdated(Transactions_Service.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.IsUpdated_Result> IsUpdatedAsync(Transactions_Service.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.GetRecIdFromKey_Result GetRecIdFromKey(Transactions_Service.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(Transactions_Service.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.Create_Result Create(Transactions_Service.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.Create_Result> CreateAsync(Transactions_Service.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.CreateMultiple_Result CreateMultiple(Transactions_Service.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.CreateMultiple_Result> CreateMultipleAsync(Transactions_Service.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.Update_Result Update(Transactions_Service.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.Update_Result> UpdateAsync(Transactions_Service.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.UpdateMultiple_Result UpdateMultiple(Transactions_Service.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.UpdateMultiple_Result> UpdateMultipleAsync(Transactions_Service.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Transactions_Service.Delete_Result Delete(Transactions_Service.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/transactions:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Service.Delete_Result> DeleteAsync(Transactions_Service.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions")]
    public partial class Transactions : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string keyField;
        
        private string transactionIdField;
        
        private string acctNoField;
        
        private decimal clearedBalanceField;
        
        private bool clearedBalanceFieldSpecified;
        
        private string currencyField;
        
        private string narrationField;
        
        private System.DateTime valueDateField;
        
        private bool valueDateFieldSpecified;
        
        private System.DateTime postingDateField;
        
        private bool postingDateFieldSpecified;
        
        private string paymentRefField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private TransactionType transactionTypeField;
        
        private bool transactionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AcctNo
        {
            get
            {
                return this.acctNoField;
            }
            set
            {
                this.acctNoField = value;
                this.RaisePropertyChanged("AcctNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal ClearedBalance
        {
            get
            {
                return this.clearedBalanceField;
            }
            set
            {
                this.clearedBalanceField = value;
                this.RaisePropertyChanged("ClearedBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearedBalanceSpecified
        {
            get
            {
                return this.clearedBalanceFieldSpecified;
            }
            set
            {
                this.clearedBalanceFieldSpecified = value;
                this.RaisePropertyChanged("ClearedBalanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Narration
        {
            get
            {
                return this.narrationField;
            }
            set
            {
                this.narrationField = value;
                this.RaisePropertyChanged("Narration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime ValueDate
        {
            get
            {
                return this.valueDateField;
            }
            set
            {
                this.valueDateField = value;
                this.RaisePropertyChanged("ValueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueDateSpecified
        {
            get
            {
                return this.valueDateFieldSpecified;
            }
            set
            {
                this.valueDateFieldSpecified = value;
                this.RaisePropertyChanged("ValueDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime PostingDate
        {
            get
            {
                return this.postingDateField;
            }
            set
            {
                this.postingDateField = value;
                this.RaisePropertyChanged("PostingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostingDateSpecified
        {
            get
            {
                return this.postingDateFieldSpecified;
            }
            set
            {
                this.postingDateFieldSpecified = value;
                this.RaisePropertyChanged("PostingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PaymentRef
        {
            get
            {
                return this.paymentRefField;
            }
            set
            {
                this.paymentRefField = value;
                this.RaisePropertyChanged("PaymentRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDateSpecified
        {
            get
            {
                return this.transactionDateFieldSpecified;
            }
            set
            {
                this.transactionDateFieldSpecified = value;
                this.RaisePropertyChanged("TransactionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("AmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public TransactionType TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionTypeSpecified
        {
            get
            {
                return this.transactionTypeFieldSpecified;
            }
            set
            {
                this.transactionTypeFieldSpecified = value;
                this.RaisePropertyChanged("TransactionTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions")]
    public enum TransactionType
    {
        
        /// <remarks/>
        EFT,
        
        /// <remarks/>
        _SWIFT,
        
        /// <remarks/>
        _RTGS,
        
        /// <remarks/>
        _C2B,
        
        /// <remarks/>
        MPESA,
        
        /// <remarks/>
        Omni_IBATS_BATCH,
        
        /// <remarks/>
        Branch_Posting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions")]
    public partial class Transactions_Filter : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private Transactions_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Transactions_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions")]
    public enum Transactions_Fields
    {
        
        /// <remarks/>
        TransactionId,
        
        /// <remarks/>
        AcctNo,
        
        /// <remarks/>
        ClearedBalance,
        
        /// <remarks/>
        Currency,
        
        /// <remarks/>
        Narration,
        
        /// <remarks/>
        ValueDate,
        
        /// <remarks/>
        PostingDate,
        
        /// <remarks/>
        PaymentRef,
        
        /// <remarks/>
        TransactionDate,
        
        /// <remarks/>
        Amount,
        
        /// <remarks/>
        TransactionType,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public string TransactionId;
        
        public Read()
        {
        }
        
        public Read(string TransactionId)
        {
            this.TransactionId = TransactionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public Transactions_Service.Transactions Transactions;
        
        public Read_Result()
        {
        }
        
        public Read_Result(Transactions_Service.Transactions Transactions)
        {
            this.Transactions = Transactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public Transactions_Service.Transactions Transactions;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(Transactions_Service.Transactions Transactions)
        {
            this.Transactions = Transactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public Transactions_Service.Transactions_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(Transactions_Service.Transactions_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Transactions_Service.Transactions[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(Transactions_Service.Transactions[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public Transactions_Service.Transactions Transactions;
        
        public Create()
        {
        }
        
        public Create(Transactions_Service.Transactions Transactions)
        {
            this.Transactions = Transactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public Transactions_Service.Transactions Transactions;
        
        public Create_Result()
        {
        }
        
        public Create_Result(Transactions_Service.Transactions Transactions)
        {
            this.Transactions = Transactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Transactions_Service.Transactions[] Transactions_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(Transactions_Service.Transactions[] Transactions_List)
        {
            this.Transactions_List = Transactions_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Transactions_Service.Transactions[] Transactions_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(Transactions_Service.Transactions[] Transactions_List)
        {
            this.Transactions_List = Transactions_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public Transactions_Service.Transactions Transactions;
        
        public Update()
        {
        }
        
        public Update(Transactions_Service.Transactions Transactions)
        {
            this.Transactions = Transactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public Transactions_Service.Transactions Transactions;
        
        public Update_Result()
        {
        }
        
        public Update_Result(Transactions_Service.Transactions Transactions)
        {
            this.Transactions = Transactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Transactions_Service.Transactions[] Transactions_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(Transactions_Service.Transactions[] Transactions_List)
        {
            this.Transactions_List = Transactions_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Transactions_Service.Transactions[] Transactions_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(Transactions_Service.Transactions[] Transactions_List)
        {
            this.Transactions_List = Transactions_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/transactions", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/transactions", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface Transactions_PortChannel : Transactions_Service.Transactions_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Transactions_PortClient : System.ServiceModel.ClientBase<Transactions_Service.Transactions_Port>, Transactions_Service.Transactions_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Transactions_PortClient() : 
                base(Transactions_PortClient.GetDefaultBinding(), Transactions_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Transactions_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Transactions_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(Transactions_PortClient.GetBindingForEndpoint(endpointConfiguration), Transactions_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Transactions_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Transactions_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Transactions_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Transactions_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Transactions_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.Read_Result Transactions_Service.Transactions_Port.Read(Transactions_Service.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public Transactions_Service.Transactions Read(string TransactionId)
        {
            Transactions_Service.Read inValue = new Transactions_Service.Read();
            inValue.TransactionId = TransactionId;
            Transactions_Service.Read_Result retVal = ((Transactions_Service.Transactions_Port)(this)).Read(inValue);
            return retVal.Transactions;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Service.Read_Result> Transactions_Service.Transactions_Port.ReadAsync(Transactions_Service.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.Read_Result> ReadAsync(string TransactionId)
        {
            Transactions_Service.Read inValue = new Transactions_Service.Read();
            inValue.TransactionId = TransactionId;
            return ((Transactions_Service.Transactions_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.ReadByRecId_Result Transactions_Service.Transactions_Port.ReadByRecId(Transactions_Service.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public Transactions_Service.Transactions ReadByRecId(string recId)
        {
            Transactions_Service.ReadByRecId inValue = new Transactions_Service.ReadByRecId();
            inValue.recId = recId;
            Transactions_Service.ReadByRecId_Result retVal = ((Transactions_Service.Transactions_Port)(this)).ReadByRecId(inValue);
            return retVal.Transactions;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Service.ReadByRecId_Result> Transactions_Service.Transactions_Port.ReadByRecIdAsync(Transactions_Service.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            Transactions_Service.ReadByRecId inValue = new Transactions_Service.ReadByRecId();
            inValue.recId = recId;
            return ((Transactions_Service.Transactions_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.ReadMultiple_Result Transactions_Service.Transactions_Port.ReadMultiple(Transactions_Service.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public Transactions_Service.Transactions[] ReadMultiple(Transactions_Service.Transactions_Filter[] filter, string bookmarkKey, int setSize)
        {
            Transactions_Service.ReadMultiple inValue = new Transactions_Service.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            Transactions_Service.ReadMultiple_Result retVal = ((Transactions_Service.Transactions_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Service.ReadMultiple_Result> Transactions_Service.Transactions_Port.ReadMultipleAsync(Transactions_Service.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.ReadMultiple_Result> ReadMultipleAsync(Transactions_Service.Transactions_Filter[] filter, string bookmarkKey, int setSize)
        {
            Transactions_Service.ReadMultiple inValue = new Transactions_Service.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((Transactions_Service.Transactions_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.IsUpdated_Result Transactions_Service.Transactions_Port.IsUpdated(Transactions_Service.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            Transactions_Service.IsUpdated inValue = new Transactions_Service.IsUpdated();
            inValue.Key = Key;
            Transactions_Service.IsUpdated_Result retVal = ((Transactions_Service.Transactions_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Service.IsUpdated_Result> Transactions_Service.Transactions_Port.IsUpdatedAsync(Transactions_Service.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            Transactions_Service.IsUpdated inValue = new Transactions_Service.IsUpdated();
            inValue.Key = Key;
            return ((Transactions_Service.Transactions_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.GetRecIdFromKey_Result Transactions_Service.Transactions_Port.GetRecIdFromKey(Transactions_Service.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            Transactions_Service.GetRecIdFromKey inValue = new Transactions_Service.GetRecIdFromKey();
            inValue.Key = Key;
            Transactions_Service.GetRecIdFromKey_Result retVal = ((Transactions_Service.Transactions_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Service.GetRecIdFromKey_Result> Transactions_Service.Transactions_Port.GetRecIdFromKeyAsync(Transactions_Service.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            Transactions_Service.GetRecIdFromKey inValue = new Transactions_Service.GetRecIdFromKey();
            inValue.Key = Key;
            return ((Transactions_Service.Transactions_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.Create_Result Transactions_Service.Transactions_Port.Create(Transactions_Service.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref Transactions_Service.Transactions Transactions)
        {
            Transactions_Service.Create inValue = new Transactions_Service.Create();
            inValue.Transactions = Transactions;
            Transactions_Service.Create_Result retVal = ((Transactions_Service.Transactions_Port)(this)).Create(inValue);
            Transactions = retVal.Transactions;
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.Create_Result> CreateAsync(Transactions_Service.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.CreateMultiple_Result Transactions_Service.Transactions_Port.CreateMultiple(Transactions_Service.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref Transactions_Service.Transactions[] Transactions_List)
        {
            Transactions_Service.CreateMultiple inValue = new Transactions_Service.CreateMultiple();
            inValue.Transactions_List = Transactions_List;
            Transactions_Service.CreateMultiple_Result retVal = ((Transactions_Service.Transactions_Port)(this)).CreateMultiple(inValue);
            Transactions_List = retVal.Transactions_List;
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.CreateMultiple_Result> CreateMultipleAsync(Transactions_Service.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.Update_Result Transactions_Service.Transactions_Port.Update(Transactions_Service.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref Transactions_Service.Transactions Transactions)
        {
            Transactions_Service.Update inValue = new Transactions_Service.Update();
            inValue.Transactions = Transactions;
            Transactions_Service.Update_Result retVal = ((Transactions_Service.Transactions_Port)(this)).Update(inValue);
            Transactions = retVal.Transactions;
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.Update_Result> UpdateAsync(Transactions_Service.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.UpdateMultiple_Result Transactions_Service.Transactions_Port.UpdateMultiple(Transactions_Service.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref Transactions_Service.Transactions[] Transactions_List)
        {
            Transactions_Service.UpdateMultiple inValue = new Transactions_Service.UpdateMultiple();
            inValue.Transactions_List = Transactions_List;
            Transactions_Service.UpdateMultiple_Result retVal = ((Transactions_Service.Transactions_Port)(this)).UpdateMultiple(inValue);
            Transactions_List = retVal.Transactions_List;
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.UpdateMultiple_Result> UpdateMultipleAsync(Transactions_Service.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Service.Delete_Result Transactions_Service.Transactions_Port.Delete(Transactions_Service.Delete request)
        {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key)
        {
            Transactions_Service.Delete inValue = new Transactions_Service.Delete();
            inValue.Key = Key;
            Transactions_Service.Delete_Result retVal = ((Transactions_Service.Transactions_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Service.Delete_Result> Transactions_Service.Transactions_Port.DeleteAsync(Transactions_Service.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Service.Delete_Result> DeleteAsync(string Key)
        {
            Transactions_Service.Delete inValue = new Transactions_Service.Delete();
            inValue.Key = Key;
            return ((Transactions_Service.Transactions_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Transactions_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Transactions_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://mcokumu:7047/DynamicsNAV110/WS/CRONUS International Ltd./Page/Transactions" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Transactions_PortClient.GetBindingForEndpoint(EndpointConfiguration.Transactions_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Transactions_PortClient.GetEndpointAddress(EndpointConfiguration.Transactions_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            Transactions_Port,
        }
    }
}
